---

- name: Install Pacman packages
  pacman:
    force: '{{ item.force | default("no") }}'
    name: '{{ item.name  }}'
    state: '{{ item.state | default("present") }}'
    upgrade: '{{ item.upgrade | default(omit) }}'
  with_items: '{{ pacman_packages }}'

...
